spring.application.name=almacen-seguridad

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/almacen_seguridad
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080

apisperu.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1heGxvcGV6YXZhbG9zMjkwNUBnbWFpbC5jb20ifQ.KLdXpN3I0wksraQrBuVu9JC4p2vY4qWjVb9Rs0HEZeY
apisperu.url.ruc=https://dniruc.apisperu.com/api/v1/ruc/
apisperu.url.dni=https://dniruc.apisperu.com/api/v1/dni/

groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions

brevo.api.key=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
brevo.api.url=https://api.brevo.com/v3/smtp/email
app.mail.remitente=maxlopezavalos2905@gmail.com

app.stock.umbral=9999


